server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_site
    username: postgres
    password: Behappy1q
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQL95Dialect

springdoc:
  swagger-ui:
    path: /swagger